// Package schemaorg loads the committed schema.org protobuf type system
// (schemaorg.fdset, generated by cmd/genast) as a reflection FileDescriptor, so
// runtime front-ends (service/jsonld, service/microdata) can build typed
// messages with dynamicpb without generated Go bindings. Type and field lookups
// are normalized (case- and separator-insensitive) so callers can look up by the
// schema.org name (e.g. "Person", "birthDate") without reconstructing gluon's
// exact pascal/snake casing.
package schemaorg

import (
	_ "embed"
	"fmt"
	"strings"
	"sync"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

//go:embed schemaorg.fdset
var fdsetBytes []byte

var (
	once     sync.Once
	file     protoreflect.FileDescriptor
	byNorm   map[string]protoreflect.MessageDescriptor // normalized message name → descriptor
	loadErr  error
	fieldIdx sync.Map // MessageDescriptor → map[string]FieldDescriptor (normalized field name)
)

func load() {
	set := &descriptorpb.FileDescriptorSet{}
	if err := proto.Unmarshal(fdsetBytes, set); err != nil {
		loadErr = fmt.Errorf("unmarshal fdset: %w", err)
		return
	}
	files, err := protodesc.NewFiles(set)
	if err != nil {
		loadErr = fmt.Errorf("build file descriptors: %w", err)
		return
	}
	files.RangeFiles(func(fd protoreflect.FileDescriptor) bool {
		file = fd
		return false // single file in the set
	})
	if file == nil {
		loadErr = fmt.Errorf("descriptor set is empty")
		return
	}
	byNorm = make(map[string]protoreflect.MessageDescriptor)
	msgs := file.Messages()
	for i := 0; i < msgs.Len(); i++ {
		md := msgs.Get(i)
		byNorm[norm(string(md.Name()))] = md
	}
}

// File returns the schema.org FileDescriptor.
func File() (protoreflect.FileDescriptor, error) {
	once.Do(load)
	return file, loadErr
}

// MessageForType returns the descriptor for a schema.org type local name
// (e.g. "Person" → message "SchemaPerson"), or nil if that type is not modeled.
func MessageForType(typeName string) (protoreflect.MessageDescriptor, error) {
	if _, err := File(); err != nil {
		return nil, err
	}
	return byNorm["schema"+norm(typeName)], nil
}

// MessageByName returns a modeled message by its (normalized) proto name, e.g.
// a property wrapper like "Address". Returns nil if absent.
func MessageByName(name string) (protoreflect.MessageDescriptor, error) {
	if _, err := File(); err != nil {
		return nil, err
	}
	return byNorm[norm(name)], nil
}

// FieldByName returns md's field matching a schema.org property name
// (case/separator-insensitive), or nil if the message has no such field.
func FieldByName(md protoreflect.MessageDescriptor, name string) protoreflect.FieldDescriptor {
	idx, ok := fieldIdx.Load(md)
	if !ok {
		m := make(map[string]protoreflect.FieldDescriptor)
		fs := md.Fields()
		for i := 0; i < fs.Len(); i++ {
			f := fs.Get(i)
			m[norm(string(f.Name()))] = f
		}
		fieldIdx.Store(md, m)
		idx = m
	}
	return idx.(map[string]protoreflect.FieldDescriptor)[norm(name)]
}

// norm lowercases and drops every non-alphanumeric character, so "SchemaPerson",
// "schema_person", and "schemaPerson" all collapse to one key.
func norm(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + ('a' - 'A'))
		}
	}
	return b.String()
}
