// Package schemaorg loads the committed schema.org protobuf type system so
// runtime front-ends (service/jsonld, service/microdata) can build typed
// Schema<Type> messages.
//
// There are two descriptor sources, and the runtime prefers the first:
//
//   - Generated Go bindings (proto/pb/schemaorg/*.pb.go). When the program links
//     them — typically via a blank import of proto/register.go — they
//     self-register their descriptors and concrete message types in the global
//     proto registry (protoregistry.GlobalFiles / GlobalTypes) at init. These are
//     preferred: resolving to them lets Build hand back the concrete
//     *schemaorgpb.Schema<Type>, which callers can type-assert.
//   - The embedded descriptor set (schemaorg.fdset, generated by cmd/genast).
//     This is protoc's input, a portable self-contained descriptor, and — here —
//     the runtime fallback: when a type is not registered (the bindings aren't
//     linked), lookups resolve against this FileDescriptor and Build constructs
//     dynamicpb messages, so the package works with no generated bindings at all.
//
// Type and field lookups are normalized (case- and separator-insensitive) so
// callers can look up by the schema.org name (e.g. "Person", "birthDate")
// without reconstructing gluon's exact pascal/snake casing.
package schemaorg

import (
	_ "embed"
	"fmt"
	"strings"
	"sync"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
)

//go:embed schemaorg.fdset
var fdsetBytes []byte

var (
	once     sync.Once
	file     protoreflect.FileDescriptor
	byNorm   map[string]protoreflect.MessageDescriptor // normalized message name → descriptor
	loadErr  error
	fieldIdx sync.Map // MessageDescriptor → map[string]FieldDescriptor (normalized field name)
)

func load() {
	set := &descriptorpb.FileDescriptorSet{}
	if err := proto.Unmarshal(fdsetBytes, set); err != nil {
		loadErr = fmt.Errorf("unmarshal fdset: %w", err)
		return
	}
	files, err := protodesc.NewFiles(set)
	if err != nil {
		loadErr = fmt.Errorf("build file descriptors: %w", err)
		return
	}
	files.RangeFiles(func(fd protoreflect.FileDescriptor) bool {
		file = fd
		return false // single file in the set
	})
	if file == nil {
		loadErr = fmt.Errorf("descriptor set is empty")
		return
	}
	byNorm = make(map[string]protoreflect.MessageDescriptor)
	msgs := file.Messages()
	for i := 0; i < msgs.Len(); i++ {
		md := msgs.Get(i)
		byNorm[norm(string(md.Name()))] = resolve(md)
	}
}

// resolve prefers the descriptor registered in the global proto registry (put
// there by the generated bindings' blank import) over the embedded-fdset
// descriptor, keying on the message's full name (e.g. "schemaorg.SchemaPerson").
// When the bindings aren't linked the registry lookup misses and the fdset
// descriptor is used — the fallback that keeps this package working on its own.
// The two descriptors describe the same message, so every downstream lookup
// (fields, oneof arms) behaves identically whichever is returned.
func resolve(fallback protoreflect.MessageDescriptor) protoreflect.MessageDescriptor {
	if d, err := protoregistry.GlobalFiles.FindDescriptorByName(fallback.FullName()); err == nil {
		if md, ok := d.(protoreflect.MessageDescriptor); ok {
			return md
		}
	}
	return fallback
}

// File returns the schema.org FileDescriptor.
func File() (protoreflect.FileDescriptor, error) {
	once.Do(load)
	return file, loadErr
}

// MessageForType returns the descriptor for a schema.org type local name
// (e.g. "Person" → message "SchemaPerson"), or nil if that type is not modeled.
func MessageForType(typeName string) (protoreflect.MessageDescriptor, error) {
	if _, err := File(); err != nil {
		return nil, err
	}
	return byNorm["schema"+norm(typeName)], nil
}

// MessageByName returns a modeled message by its (normalized) proto name, e.g.
// a property wrapper like "Address". Returns nil if absent.
func MessageByName(name string) (protoreflect.MessageDescriptor, error) {
	if _, err := File(); err != nil {
		return nil, err
	}
	return byNorm[norm(name)], nil
}

// FieldByName returns md's field matching a schema.org property name
// (case/separator-insensitive), or nil if the message has no such field.
func FieldByName(md protoreflect.MessageDescriptor, name string) protoreflect.FieldDescriptor {
	idx, ok := fieldIdx.Load(md)
	if !ok {
		m := make(map[string]protoreflect.FieldDescriptor)
		fs := md.Fields()
		for i := 0; i < fs.Len(); i++ {
			f := fs.Get(i)
			m[norm(string(f.Name()))] = f
		}
		fieldIdx.Store(md, m)
		idx = m
	}
	return idx.(map[string]protoreflect.FieldDescriptor)[norm(name)]
}

// norm lowercases and drops every non-alphanumeric character, so "SchemaPerson",
// "schema_person", and "schemaPerson" all collapse to one key.
func norm(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + ('a' - 'A'))
		}
	}
	return b.String()
}
